In [1]:
import numpy as np

The equations are as follow:
                                            
3 x1 − 0.1 x2 − 0.2 x3 = 7.85

0.1 x1 + 7 x2 − 0.3 x3 = −19.3

0.3 x1     − 0.2 x2 − 10 x3 = 71.4

In [2]:
def matrix(n):
    a = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            a[i,j] = float(input())
    return a

def b(n):
    a = np.zeros((n,1))
    for i in range(n):
        a[i,0]=float(input())
    return a

In [3]:
n = 3
# m = matrix(n)
# b = b(n)
m = np.array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

b = np.array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

In [4]:
mat = m.copy()
mat

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [5]:
b1 = b.copy()
b1

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

Write a program to employ LU decomposition to get the solution.
Check your answers by substituting them into the original equation.

In [6]:
def LU_decomp(m): 
    n, n = m.shape
    l = np.identity(n)
    for i in range(n-1):
        for j in range(i+1,n):
            fact = m[j,i]/m[i,i]
            l[j,i] = fact
            for k in range(i,n):
                m[j,k] = m[j,k] - fact * m[i,k]
    return m, l

In [7]:
u, l = LU_decomp(mat)

In [8]:
u

array([[ 3.        , -0.1       , -0.2       ],
       [ 0.        ,  7.00333333, -0.29333333],
       [ 0.        ,  0.        , -9.98795812]])

In [9]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.03333333,  1.        ,  0.        ],
       [ 0.1       , -0.02712994,  1.        ]])

In [10]:
np.dot(l,u) # After substituting them together

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [11]:
def d(l,b):
    n,_ = l.shape
    d = np.zeros((n,1))
    for j in range(n):
            d[j] = b[j]
            for k in range(j):
                d[j] -= l[j,k]*d[k]
    return d

In [12]:
d(l,b1)

array([[  7.85      ],
       [-19.56166667],
       [ 70.08429319]])

In [13]:
def x(u,l,b,d):
    n,_ = u.shape
    x = np.zeros((3,1))
    z1 = d(l,b)
    for i in range(n):
        x[n-1-i] = z1[n-1-i]/u[n-1-i,n-1-i]
        for j in range(i):
            x[n-1-i] -= (u[n-1-i,n-1-j] * x[n-1-j]) / u[n-1-i,n-1-i]
    return x

In [14]:
x = x(u,l,b1,d)
x

array([[ 2.04597159],
       [-3.08709441],
       [-7.01687896]])

In [15]:
m1 = m.copy()
m1

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [16]:
np.dot(m1,x) #Equal to b => Ax - B = 0

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

Find the inverse of the matrix [A] made up of the L.H.S of the above equation. Check your
answer by multiplying it by original matrix.

In [17]:
def z(l, a):
    c = np.identity(3)
    z = np.zeros((3,1))
    for j in range(n):
            z[j] = c[j,a]
            for k in range(j):
                z[j] -= l[j,k]*z[k]
    return z


In [18]:
z(l, 0)

array([[ 1.        ],
       [-0.03333333],
       [-0.10090433]])

In [19]:
z(l,1)

array([[0.        ],
       [1.        ],
       [0.02712994]])

In [20]:
z(l,2)

array([[0.],
       [0.],
       [1.]])

In [21]:
def x(u,l,a):
    n,_ = u.shape
    x = np.zeros((3,1))
    z1 = z(l,a)
    for i in range(n):
        x[n-1-i] = z1[n-1-i]/u[n-1-i,n-1-i]
        for j in range(i):
            x[n-1-i] -= (u[n-1-i,n-1-j] * x[n-1-j]) / u[n-1-i,n-1-i]
    return x



In [22]:
def inverse_lu(l,u,x):
    n,_ = m.shape
    x_list = []
    for i in range(n):
        x1 = x(u,l,i)
        x_list.append(x1)
    x = np.zeros((n,n))
    for i in range(n):
        x_1 = x_list[i]
        x[:,i] = x_1[:,0]
    return x

def inverse_m_usingLU(m,x):
    u, l = LU_decomp(m)
    n,_ = m.shape
    x_list = []
    for i in range(n):
        x1 = x(u,l,i)
        x_list.append(x1)
    x = np.zeros((n,n))
    for i in range(n):
        x_1 = x_list[i]
        x[:,i] = x_1[:,0]
    return x

In [23]:
m1 = m.copy()
inverse_m_usingLU(m1,x)

array([[ 0.33386229,  0.00457476, -0.00681449],
       [-0.00433649,  0.14267538, -0.00419353],
       [ 0.0101026 , -0.00271626, -0.10012056]])

In [24]:
inverse_lu(l,u, x)

array([[ 0.33386229,  0.00457476, -0.00681449],
       [-0.00433649,  0.14267538, -0.00419353],
       [ 0.0101026 , -0.00271626, -0.10012056]])

In [26]:
m1 = m.copy()
m_1 = inverse_m_usingLU(m,x)
np.dot(m1,m_1) #Almost equal to Identity, the upper tringular matrix is close to 0 (10^(-18) -> 0)

array([[ 1.00000000e+00,  5.95139782e-19, -1.66399601e-18],
       [ 0.00000000e+00,  1.00000000e+00,  3.94147021e-18],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])