In [470]:
import numpy as np

The equations are as follow:
                                            
3 x1 − 0.1 x2 − 0.2 x3 = 7.85

0.1 x1 + 7 x2 − 0.3 x3 = −19.3

0.3 x1     − 0.2 x2 − 10 x3 = 71.4

In [471]:
def matrix(n):
    a = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            a[i,j] = float(input())
    return a

In [472]:
def b(n):
    a = np.zeros((3,1))
    for i in range(n):
        a[i,0]=float(input())
    return a

In [473]:
n= 3
# m = matrix(n)
# b = b(n)  
# If you want to change the values then use this function 

In [474]:
m = np.array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

b = np.array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

In [475]:
mat = m.copy()
mat

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [476]:
b1 = b.copy()
b1

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

Write a program to employ Naive Gauss elimination to get the solution.
Print all matrices at all the step of elimination. Check your answers by substituting them into the original
equation. Count the number of FLOPs required in this.

In [477]:
def naive_gauss_elim(m): 
    n, n = m.shape   
    f = 0
    for i in range(n-1):
        for j in range(i+1,n):
            fact = m[j,i]/m[i,i]
            f += 1
            for k in range(i,n):
                m[j,k] = m[j,k] - fact * m[i,k]
                f += 2
            b1[j] = b1[j] - fact * b1[i]
            f += 2
    return m, f

In [478]:
mat1, flop1 = naive_gauss_elim(mat)
mat1

array([[ 3.        , -0.1       , -0.2       ],
       [ 0.        ,  7.00333333, -0.29333333],
       [ 0.        ,  0.        , -9.98795812]])

In [479]:
b1

array([[  7.85      ],
       [-19.56166667],
       [ 70.08429319]])

In [480]:
def backward(mat,b):
        f=0
        x = np.zeros((n,1))
        for i in range(n):
                x[n-1-i] = (b[n-1-i] - np.dot(mat[n-1-i, n-i:] ,x[n-i:])) / mat[n-1-i, n-1-i]
                f += 3 # 1 sub 1 div 1 in dot product
        return x, f

In [481]:
x1, flop2 = backward(mat1, b1)
x1

array([[ 2.04597159],
       [-3.08709441],
       [-7.01687896]])

In [482]:
print(f"Total FLOPs are {flop1+flop2}")

Total FLOPs are 34


In [483]:
np.dot(m, x1) #It is equal to b1 after substitution 

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

Use pivoting to solve the above and check your answers by substituting them into the original
equation.

In [484]:
mat2 = m.copy()
mat2

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [485]:
b2 = b.copy()
b2

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

In [486]:
def find(m,v):
    n, s = m.shape
    for i in range(n):
        for j in range(s):
            if m[i,j] == v:
                return i,j
def piviot(m, b):
    f = 0
    n,_ = m.shape
    m1 = m.copy()
    for i in range(n-1):
        a = m[i:,i:].max()
        x,y = find(m,a)
        print(f"Before Swapping \n{m}\n{b}\n\n")
        # m[:,i], m[:,y] = m[:,y] , m[:,i]
        v = m[:,i].copy()
        m[:, i] = m[:,y]
        m[:,y] = v
        v = m1[:,i].copy()
        m1[:, i] = m1[:,y]
        m1[:,y] = v
        # m[i,:], m[x,:] = m[x,:], m[i,:]
        v = m[i,:].copy()
        m[i,:] = m[x,:]
        m[x,:] = v
        v = m1[i,:].copy()
        m1[i,:] = m1[x,:]
        m1[x,:] = v
        # b[i], b[x] = b[x], b[i]
        v = b[i].copy()
        b[i] = b[x]
        b[x] = v
        print(f"After Swapping\n {m}\n{b}\n\n")
        for j in range(i+1,n):
            fact = m[j,i]/m[i,i]
            f += 1
            for k in range(i,n):
                m[j,k] = m[j,k] - fact * m[i,k]
                f += 2
            b[j] = b[j] - fact * b[i]
            f += 2
    return m, b,f, m1


In [487]:
mat2, b2, flop1, matrix_after_swap = piviot(mat2, b2)

Before Swapping 
[[  3.   -0.1  -0.2]
 [  0.1   7.   -0.3]
 [  0.3  -0.2 -10. ]]
[[  7.85]
 [-19.3 ]
 [ 71.4 ]]


After Swapping
 [[  7.    0.1  -0.3]
 [ -0.1   3.   -0.2]
 [ -0.2   0.3 -10. ]]
[[-19.3 ]
 [  7.85]
 [ 71.4 ]]


Before Swapping 
[[  7.           0.1         -0.3       ]
 [  0.           3.00142857  -0.20428571]
 [  0.           0.30285714 -10.00857143]]
[[-19.3       ]
 [  7.57428571]
 [ 70.84857143]]


After Swapping
 [[  7.           0.1         -0.3       ]
 [  0.           3.00142857  -0.20428571]
 [  0.           0.30285714 -10.00857143]]
[[-19.3       ]
 [  7.57428571]
 [ 70.84857143]]




In [488]:
matrix_after_swap

array([[  7. ,   0.1,  -0.3],
       [ -0.1,   3. ,  -0.2],
       [ -0.2,   0.3, -10. ]])

In [489]:
mat2

array([[ 7.        ,  0.1       , -0.3       ],
       [ 0.        ,  3.00142857, -0.20428571],
       [ 0.        ,  0.        , -9.98795812]])

In [490]:
b2

array([[-19.3       ],
       [  7.57428571],
       [ 70.08429319]])

In [491]:
x2, flop2 = backward(mat2, b2)

In [492]:
x2

array([[-3.08709441],
       [ 2.04597159],
       [-7.01687896]])

In [493]:
np.dot(matrix_after_swap, x2)

array([[-19.3 ],
       [  7.85],
       [ 71.4 ]])

Use the Gausee-Jordan technique to solve the above. Count the number of FLOPs required in
this.

In [494]:
mat3 = m.copy()
mat3

array([[  3. ,  -0.1,  -0.2],
       [  0.1,   7. ,  -0.3],
       [  0.3,  -0.2, -10. ]])

In [495]:
b3 = b.copy()
b3

array([[  7.85],
       [-19.3 ],
       [ 71.4 ]])

In [496]:
def gausee_jordan(m, b):
    n, _ = m.shape
    f = 0
    for i in range(n-1):
        for j in range(i+1,n):
            fact = m[j,i]/m[i,i]
            f += 1
            for k in range(i,n):
                m[j,k] = m[j,k] - fact * m[i,k]
                f += 2
            b[j] = b[j] - fact * b[i]
            f += 2
    for i in range(n-1):
        for j in range(i+1, n):
            fact = m[n-1-j, n-1-i]/m[n-1-i,n-1-i]
            f +=1
            for k in range(i,n):
                m[n-1-j, n-1-k] = m[n-1-j, n-1-k] - fact * m[n-1-i,n-1-k]
                f += 2
            b[n-1-j] = b[n-1-j] - fact * b[n-1-i]
            f += 2
    return m,b,f

        

In [497]:
mat3 , b3, flop1 = gausee_jordan(mat3, b)

In [498]:
mat3

array([[ 3.        ,  0.        ,  0.        ],
       [ 0.        ,  7.00333333,  0.        ],
       [ 0.        ,  0.        , -9.98795812]])

In [499]:
b3

array([[  6.13791477],
       [-21.61995116],
       [ 70.08429319]])

In [500]:
def back_jordan(m,b):
    n, _ = m.shape
    x = np.zeros((n,1))
    f = 0
    for i in range(n):
        x[i] = b[i]/m[i,i]
        f += 1
    return x, f


In [501]:
x3,flop2 = back_jordan(mat3, b3)

In [502]:
x3

array([[ 2.04597159],
       [-3.08709441],
       [-7.01687896]])

In [503]:
print(f"The FLOP for gauss jordan is {flop1 + flop2}")

The FLOP for gauss jordan is 53
